version: '3.9'
services:
  vue-press:
    build: docker/vue-press
    ports:
      - "8080:8080"
    volumes:
      - ./documents:/documents
    tty: true
    command: bash -c "yarn install && yarn docs:dev"